### ISSUE TITLE
macos issue

### ISSUE THREAD

**Issue by fpereira1** [Chun-Yang/vim-textobj-chunk#1]
after installing this plugin on macos/macvim/vim8 `dac` or `vac` doesn't do anything. 

![vim_cic](https://cloud.githubusercontent.com/assets/868423/21954133/f0286124-daad-11e6-8179-cea3f2740914.gif)

is there a known issue?

**Comment by Chun-Yang** [comment]
Hi @fpereira1 , please install [vim-textobj-user](https://github.com/kana/vim-textobj-user) first.
Let me know if it works.

Thanks for trying out this plugin 😄

**Comment by fpereira1** [comment]
hey @Chun-Yang - it  works now.  I had vim texobj-user installed after I installed your plugin, it seems that when I installed vim-textobj-user first it worked.  It's nice to have a plugin for this.  I used to do `da{dd` for the, now `dac`. Thanks for the plugin! 👍

**Comment by fpereira1** [comment]
This plugin is excellent.  Thanks for sharing it.  I use it multiple times a day when working in javascript. Deleting a whole function is as easy as `dac`, replaces what I used to do `da{dd`
